version: "3.9"

services:
  bwapp:
    build: .
    container_name: bwapp
    restart: unless-stopped
    # Comment port to make bwapp accesible only via reverse proxy
    ports:
      - "8080:80"
    volumes:
      - bwapp_data:/var/lib/mysql

  nginx:
    image: owasp/modsecurity-crs:nginx
    container_name: nginx
    environment:
      - BACKEND=http://bwapp:80/
      - MODSEC_RULE_ENGINE=On
      - PARANOIA=1
      - PORT=8080
      - SSL_PORT=8443
      - CERTIFICATE_TYPE=SELF_SIGNED
      - RATE_LIMIT=${RATE_LIMIT}
      - BURST_LIMIT=${BURST_LIMIT}
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./nginx/templates/conf.d/ratelimit.conf.template:/etc/nginx/templates/conf.d/ratelimit.conf.template:ro
      - ./nginx/templates/includes/proxy_backend.conf.template:/etc/nginx/templates/includes/proxy_backend.conf.template:ro

volumes:
  bwapp_data:
